package core

// **************************************
// AUTO GENERATED BY BASE_STATS_PARSER.PY
// **************************************

const ExpertisePerQuarterPercentReduction = 2.500000

// Crit/Hit/Haste ratings are straight percentage values in classic
const HasteRatingPerHastePercent = 1
const CritRatingPerCritChance = 1
const SpellCritRatingPerCritChance = 1
const MeleeHitRatingPerHitChance = 1
const SpellHitRatingPerHitChance = 1
const DefenseRatingPerDefense = 1.500000
const DodgeRatingPerDodgeChance = 13.800001
const ParryRatingPerParryChance = 13.800001
const BlockRatingPerBlockChance = 5.000000
const ResilienceRatingPerCritReductionChance = 28.750002
