export declare const CHARACTER_LEVEL = 80;
export declare const BOSS_LEVEL: number;
export declare const EXPERTISE_PER_QUARTER_PERCENT_REDUCTION: number;
export declare const EXPERTISE_RATING_PER_EXPERTISE = 8.196;
export declare const MELEE_CRIT_RATING_PER_CRIT_CHANCE = 45.91;
export declare const MELEE_HIT_RATING_PER_HIT_CHANCE = 32.79;
export declare const SPELL_CRIT_RATING_PER_CRIT_CHANCE = 45.91;
export declare const SPELL_HIT_RATING_PER_HIT_CHANCE = 26.23;
export declare const HASTE_RATING_PER_HASTE_PERCENT = 32.79;
export declare const DEFENSE_RATING_PER_DEFENSE = 2.3654;
export declare const MISS_DODGE_PARRY_BLOCK_CRIT_CHANCE_PER_DEFENSE = 0.04;
export declare const BLOCK_RATING_PER_BLOCK_CHANCE = 7.8846;
export declare const DODGE_RATING_PER_DODGE_CHANCE = 18.9231;
export declare const PARRY_RATING_PER_PARRY_CHANCE = 23.6538;
export declare const RESILIENCE_RATING_PER_CRIT_REDUCTION_CHANCE = 39.4231;
export declare const RESILIENCE_RATING_PER_CRIT_DAMAGE_REDUCTION_PERCENT: number;
